name: tanam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  # awesome_notifications: ^0.9.3+1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_mobile_ads: ^5.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image: ^4.1.7
  mqtt_client: ^10.2.1
  ndialog: ^4.3.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  syncfusion_flutter_charts: ^26.1.39
  video_player: ^2.8.6
  web_socket_channel: ^3.0.0
  flutter_image: ^4.1.11
  tflite_flutter: ^0.10.4
  image_picker: ^1.1.2
  image_cropper: ^7.0.4
  permission_handler: ^11.3.1
  dotted_border: ^2.1.0
  path: ^1.9.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  mime: ^1.0.5
  intl: ^0.19.0
  syncfusion_flutter_sliders: ^26.1.39
  local_auth: ^2.2.0
  mongo_dart: ^0.10.3
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_speed_dial: ^7.0.0
  cookie_jar: ^4.0.8
  flutter_session_jwt: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 
    - env/.env
