// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-e-n-R6_OyGE4P3FeYKHOz2Zu3PZ8WSM',
    appId: '1:249580350729:web:420bd4e443c89d298037d8',
    messagingSenderId: '249580350729',
    projectId: 'tanamfirebase-3c545',
    authDomain: 'tanamfirebase-3c545.firebaseapp.com',
    storageBucket: 'tanamfirebase-3c545.appspot.com',
    measurementId: 'G-LQBFMGQQWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUJSZxmTukY7BQo5iFPZ5TY15-egSGwc',
    appId: '1:249580350729:android:34330a79b16bc90f8037d8',
    messagingSenderId: '249580350729',
    projectId: 'tanamfirebase-3c545',
    storageBucket: 'tanamfirebase-3c545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-5WXDwV93zpMeXhdPImyiTTOtRSF5DCg',
    appId: '1:249580350729:ios:237e6e0c9f1964868037d8',
    messagingSenderId: '249580350729',
    projectId: 'tanamfirebase-3c545',
    storageBucket: 'tanamfirebase-3c545.appspot.com',
    iosBundleId: 'com.example.tanam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-5WXDwV93zpMeXhdPImyiTTOtRSF5DCg',
    appId: '1:249580350729:ios:237e6e0c9f1964868037d8',
    messagingSenderId: '249580350729',
    projectId: 'tanamfirebase-3c545',
    storageBucket: 'tanamfirebase-3c545.appspot.com',
    iosBundleId: 'com.example.tanam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-e-n-R6_OyGE4P3FeYKHOz2Zu3PZ8WSM',
    appId: '1:249580350729:web:5ad1496a846de0368037d8',
    messagingSenderId: '249580350729',
    projectId: 'tanamfirebase-3c545',
    authDomain: 'tanamfirebase-3c545.firebaseapp.com',
    storageBucket: 'tanamfirebase-3c545.appspot.com',
    measurementId: 'G-CGGR1E0NMG',
  );

}